"""making updating nullable

Revision ID: 75442650b47d
Revises: 2993ea01b9fc
Create Date: 2025-02-28 13:57:24.384411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75442650b47d'
down_revision: Union[str, None] = '2993ea01b9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blocks', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
