"""adding relationship to workspaces model

Revision ID: 933db22d387f
Revises: 6a79e1bee67d
Create Date: 2025-02-23 22:30:28.475766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933db22d387f'
down_revision: Union[str, None] = '6a79e1bee67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspaces', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'user_id')
    # ### end Alembic commands ###
