"""new columns to the documents table, better version

Revision ID: 9aa1b43e1d5f
Revises: 75442650b47d
Create Date: 2025-03-18 15:21:48.417474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa1b43e1d5f'
down_revision: Union[str, None] = '75442650b47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), server_default='no edited', nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'assigned_to')
    # ### end Alembic commands ###
