"""adding documents and blocks models to the db

Revision ID: 9c7fa38b84b6
Revises: 933db22d387f
Create Date: 2025-02-24 15:06:28.399756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7fa38b84b6'
down_revision: Union[str, None] = '933db22d387f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
